accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .views import SignUpView
from . import views
from accounts.forms import LoginForm,SignUpForm
app_name = 'accounts'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('login/', LoginView.as_view(), name='login'),
    

]

pyshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "pyshop"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls'),name='dom'),
    path('accounts/', include('accounts.urls')), # new
    path('accounts/', include('django.contrib.auth.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <div class="jumbotron jumbotron-fluid text-center" style = "margin-bottom:0px;">
      <div class="container">
        <h1 class="display-4">O nas</h1>
    <p class="lead">Poznajmy się</p>
      </div>
    </div>
    <div class="container-fluid">
    	<div class="obrazek" style = "width:30%; float:left; padding-top:100px; position:relative; right:33px; ">
    		<img src="{% static 'ksionszka.png' %}" width = "160px" height = "180px" >
    	</div>
    	<div class = "tekst" style = "width:70%; padding-bottom:100px; float:left;">
    		<div class = "tekst1" style ="width:60%; padding-top:70px;">
     			<p style= "text-align:center; font-size:20px; font-family:Constantia;">Jesteśmy zespołem studentów z Uniwersytetu Szczecińskiego, w składzie : Dajana Wiczarska, Patrycja Suduł, Lidia Strużyna, Adrian Eret oraz Jakub Szewczyk. Serwis został stworzony na potrzeby zajęć uczelnianych. Każdy z nas interesuje się troche czymś innym i każdy z nas dodał do projektu coś od siebie. Jest to rezultat współpracy, a przyświeca mu idea łatwiejszego i szerszego dostępu do wszelkich materiałów edukacyjnych.</p>
     		</div>
     	</div>
    </div>


{% endblock %}

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>PodajDalej</title>
    {% block head %}
    {% endblock %}
    {% block navbar %}
  </head>
  <body style="background: #fdfdfd;">
    <!DOCTYPE html>
    <html>
    <head>
      <title>PodajDalej</title>
      <!-- Font Awesome -->
      <link rel="stylesheet" type="text/css" href="{% static 'fontawesome-free/css/all.min.css' %}" />
      <!-- Bootstrap 4 CSS -->
      <link rel="stylesheet" type="text/css" href="{% static 'bs4/bootstrap.min.css' %}" />
      <!-- Main Jquery -->
      <script type="text/javascript" src="{% static 'jquery.min.js' %}"></script>
      <!-- Bootstrap 4 JS -->
      <script type="text/javascript" src="{% static 'bs4/bootstrap.min.js' %}"></script>
      <!-- CustomJs -->
      <link rel="stylesheet" type="text/css" href="{% static 'custom.css' %}" />
      <script type="text/javascript" src="{% static 'custom.js' %}"></script>
    </head>
    <body>
      <nav class="navbar navbar-expand-lg navbar-dark bg-danger">
        <div class="container">
          <a class="navbar-brand" href="{% url 'home' %}">Strona główna</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">

            <form action="{% url 'home' %}" method="POST" class="form-inline my-2 my-lg-0">
              {% csrf_token %} 
              <input type="text" name="name" class="form-control" placeholder="szukaj">
              <div class="input-group-append">
              <input type="submit" name="submit" value="Szukaj" class="btn btn-dark" id="button-addon2">
          </form>

              </div>
            </div>
            </form>
            <ul class="navbar-nav ml-auto">

            {% if user.is_authenticated %}
            
            <li class="nav-item">
              <a class="nav-link text-white" href="{% url 'new' %}">Dodaj nowy produkt </a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-white" href="{% url 'cartview' %}"><i class="fa fa-shopping-cart"></i> Koszyk {{request.session.cart|length}}</a>
            </li>
              <li class="nav-item">
                <a class="nav-link text-white" href="{% url 'accounts:logout' %}">Wyloguj</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link text-white" href="{% url 'accounts:login' %}">Zaloguj</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-white" href="{% url 'accounts:signup' %}">Zarejestruj</a>
              </li>
            {% endif %}
            </ul>
          </div>
        </div>
        </nav>
        {% endblock%}

    <main>
        {% block content %}

        {% endblock %}
    </main>

<!--        <p>New to Bootstrap? <a href="https://getbootstrap.com/">Visit the homepage</a> or read our <a href="/docs/4.3/getting-started/introduction/">getting started guide</a>.</p>-->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <!-- Footer -->
  {% block footer %}
<footer class="text-center text-lg-start bg-light text-muted">
  <!-- Section: Social media -->
  <!-- Section: Social media -->

  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>PodajDalej
          </h6>
          <p>
            PodajDalej jest firmą zajmującą się sprzedażą książek z siedzibą online
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Użyteczne linki
          </h6>
          <p>
            <a href="{% static 'pp.pdf' %}" class="text-reset">Ogólne warunki korzystania</a>
          </p>
          <p>
            <a href="{% url 'contact' %}" class="text-reset">Konakt z nami</a>
          </p>
          <p>
            <a href="{% url 'onas' %}" class="text-reset">O nas</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Kontakt
          </h6>
          <p>
            <i class="fas fa-envelope me-3"></i>
            podajdalejstrona@gmail.com
          </p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2021 Copyright:
    <a class="text-reset fw-bold" href="">PodajDalej</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->
  </body>
</html>
{% endblock %}

templates/cart.html
{% extends 'base.html' %}

{% load static %}
{% load cart_tag %}

{% block content %}

<div class="jumbotron jumbotron-fluid text-center">
  </div>

  <div class="container">
      <div class="row">
{% for key,value in request.session.cart.items %}
<div class="col-md-3" style="margin-bottom: 10px; padding: 0px 5px;">
    <div class="card">
        <div style="background: #020202 url({{ value.image }}); background-size: cover; background-position: center; background-repeat: no-repeat; width: 100%; height: 250px;"></div>
        <div class="card-body">
            <h5 class="card-title">{{ value.name }} - <strong>{{ value.price }} zł</strong></h5>
            <p class="card-text">{{ value.describe }}</p>
            <p class="card-text">Kategoria: {{ value.category }}</p>
            <a href="#" class="btn btn-warning">Usuń</a>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

templates/login.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
<div id="login">
    <form class="form-horizontal" name="LoginForm" action="/login/" method="post">
    {% csrf_token %}
    {% if next %}
        <input type="hidden" name="next" value="{{ next }}" />
    {% endif %}
    <div class="control-group">
        <label class="control-label" for="username">Username</label>
        <div class="controls">
            <input type="text" id="username" name="username"  placeholder="Username">
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="password">Password</label>
        <div class="controls">
            <input type="password" name="password" id="password" placeholder="Password">
        </div>
    </div>
    <div class="control-group">
        <div class="controls">
            <button type="submit" class="btn">Login</button>
        </div>
    </div>
    </form>
</div>